# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Cars-microservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7b1dbd1f63664e88a1b5dc1952dd905c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_06eab4bdc98e460c8805d12352397ecc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7b1dbd1f63664e88a1b5dc1952dd905c }}/Cars-microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Cars-microservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9423919ab61f4df0b744399de9afb5ae }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7b1dbd1f63664e88a1b5dc1952dd905c }}/Cars-microservice:${{ github.sha }}'